spring.application.name=payroll.lite
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:2015/payroll_lite
spring.datasource.username=postgres
spring.datasource.password=020150
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=your-super-secret-key-your-super-secret-key
jwt.expiration=86400000