package com.tino.payroll.lite.enums;

public enum AuditAction {
    ADMIN_BOOTSTRAPPED,
    USER_REGISTERED,
    USER_ROLE_CHANGED,
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_DELETED,
    NSSA_RULE_CREATED,
    NSSA_RULE_UPDATED,
    PAYE_TABLE_CREATED,
    PAYE_TABLE_UPDATED,
    RECURRING_PAY_ITEM_CREATED,
    RECURRING_PAY_ITEM_UPDATED,
    PAYROLL_RUN_CREATED,
    PAYROLL_RUN_PROCESSED,
    PAYROLL_ADJUSTMENT_CREATED,
    PAYROLL_ADJUSTMENT_DELETED,
    PAYSLIP_DOWNLOADED
}
