-- Payroll Lite V1 schema baseline for PostgreSQL.
-- Flyway is the only component allowed to create or alter the database schema.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    job_title VARCHAR(255),
    basic_salary NUMERIC(12, 2) NOT NULL,
    salary_currency VARCHAR(255) NOT NULL,
    hire_date DATE,
    status VARCHAR(255) NOT NULL,
    user_id BIGINT,
    CONSTRAINT uk_employees_employee_number UNIQUE (employee_number),
    CONSTRAINT uk_employees_email UNIQUE (email),
    CONSTRAINT uk_employees_user UNIQUE (user_id),
    CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE nssa_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_version VARCHAR(255) NOT NULL,
    currency VARCHAR(255) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    employee_rate NUMERIC(8, 6) NOT NULL,
    employer_rate NUMERIC(8, 6) NOT NULL,
    pensionable_earnings_ceiling NUMERIC(18, 2) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_nssa_rules_version UNIQUE (rule_version),
    CONSTRAINT uk_nssa_rule_currency_effective_from UNIQUE (currency, effective_from)
);

CREATE TABLE paye_tax_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_version VARCHAR(100) NOT NULL,
    currency VARCHAR(255) NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    aids_levy_rate NUMERIC(8, 6) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_paye_tax_tables_version UNIQUE (rule_version),
    CONSTRAINT uk_paye_table_currency_effective_from UNIQUE (currency, effective_from)
);

CREATE TABLE paye_tax_bands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_table_id BIGINT NOT NULL,
    lower_bound NUMERIC(18, 2) NOT NULL,
    upper_bound NUMERIC(18, 2),
    tax_rate NUMERIC(8, 6) NOT NULL,
    CONSTRAINT uk_paye_band_table_lower_bound UNIQUE (tax_table_id, lower_bound),
    CONSTRAINT fk_paye_bands_table FOREIGN KEY (tax_table_id) REFERENCES paye_tax_tables (id)
);

CREATE TABLE payroll_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    currency VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    processed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uk_payroll_run_period UNIQUE (month, year, currency)
);

CREATE TABLE payroll_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_run_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    description VARCHAR(100) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    taxable BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_payroll_adjustments_run FOREIGN KEY (payroll_run_id) REFERENCES payroll_runs (id),
    CONSTRAINT fk_payroll_adjustments_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE recurring_pay_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    description VARCHAR(100) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    taxable BOOLEAN NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_recurring_pay_items_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE INDEX idx_recurring_pay_item_employee_dates
    ON recurring_pay_items (employee_id, effective_from, effective_to);

CREATE TABLE payslips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    payroll_run_id BIGINT NOT NULL,
    basic_salary NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(255) NOT NULL,
    gross_salary NUMERIC(12, 2) NOT NULL,
    pensionable_earnings NUMERIC(12, 2) NOT NULL,
    nssa_deduction NUMERIC(12, 2) NOT NULL,
    employer_nssa_contribution NUMERIC(12, 2) NOT NULL,
    nssa_rule_version VARCHAR(100) NOT NULL,
    paye_deduction NUMERIC(12, 2) NOT NULL,
    taxable_income NUMERIC(12, 2),
    income_tax_before_credits NUMERIC(12, 2),
    tax_credits_applied NUMERIC(12, 2),
    aids_levy NUMERIC(12, 2),
    paye_rule_version VARCHAR(100),
    total_deductions NUMERIC(12, 2) NOT NULL,
    net_salary NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_payslip_employee_payroll_run UNIQUE (employee_id, payroll_run_id),
    CONSTRAINT fk_payslips_employee FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT fk_payslips_run FOREIGN KEY (payroll_run_id) REFERENCES payroll_runs (id)
);

CREATE TABLE payslip_line_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payslip_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    description VARCHAR(100) NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    taxable BOOLEAN NOT NULL,
    source VARCHAR(20),
    CONSTRAINT fk_payslip_line_items_payslip FOREIGN KEY (payslip_id) REFERENCES payslips (id)
);
