-- Append-only business audit trail. Actor data is stored as a snapshot rather
-- than a foreign key so history survives account or employee lifecycle changes.

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    actor_email VARCHAR(255) NOT NULL,
    actor_role VARCHAR(20),
    action VARCHAR(60) NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id BIGINT,
    details VARCHAR(500) NOT NULL,
    occurred_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_audit_events_actor_role CHECK (
        actor_role IS NULL OR actor_role IN ('ADMIN', 'HR', 'EMPLOYEE')
    ),
    CONSTRAINT ck_audit_events_action CHECK (action IN (
        'ADMIN_BOOTSTRAPPED',
        'USER_REGISTERED',
        'USER_ROLE_CHANGED',
        'EMPLOYEE_CREATED',
        'EMPLOYEE_UPDATED',
        'EMPLOYEE_DELETED',
        'NSSA_RULE_CREATED',
        'NSSA_RULE_UPDATED',
        'PAYE_TABLE_CREATED',
        'PAYE_TABLE_UPDATED',
        'RECURRING_PAY_ITEM_CREATED',
        'RECURRING_PAY_ITEM_UPDATED',
        'PAYROLL_RUN_CREATED',
        'PAYROLL_RUN_PROCESSED',
        'PAYROLL_ADJUSTMENT_CREATED',
        'PAYROLL_ADJUSTMENT_DELETED',
        'PAYSLIP_DOWNLOADED'
    )),
    CONSTRAINT ck_audit_events_entity_type CHECK (entity_type IN (
        'USER',
        'EMPLOYEE',
        'NSSA_RULE',
        'PAYE_TABLE',
        'RECURRING_PAY_ITEM',
        'PAYROLL_RUN',
        'PAYROLL_ADJUSTMENT',
        'PAYSLIP'
    ))
);

CREATE INDEX idx_audit_events_occurred_at
    ON audit_events (occurred_at DESC, id DESC);
CREATE INDEX idx_audit_events_actor_email
    ON audit_events (LOWER(actor_email));
CREATE INDEX idx_audit_events_entity
    ON audit_events (entity_type, entity_id);
CREATE INDEX idx_audit_events_action
    ON audit_events (action);

CREATE FUNCTION prevent_audit_event_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'audit_events is append-only; % is not allowed', TG_OP;
END;
$$;

CREATE TRIGGER trg_prevent_audit_event_mutation
BEFORE UPDATE OR DELETE ON audit_events
FOR EACH ROW
EXECUTE FUNCTION prevent_audit_event_mutation();
